In [1]:
import pandas as pd
import numpy as np
#from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv("../Dataset/heart_disease_uci.csv")
df = dataset.copy()
dataset.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [6]:
print(df.shape)

df.info()

(920, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [7]:
for col in ["sex","dataset","cp","fbs","restecg","exang","slope","thal"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 sex
sex
Male      726
Female    194
Name: count, dtype: int64

 dataset
dataset
Cleveland        304
Hungary          293
VA Long Beach    200
Switzerland      123
Name: count, dtype: int64

 cp
cp
asymptomatic       496
non-anginal        204
atypical angina    174
typical angina      46
Name: count, dtype: int64

 fbs
fbs
False    692
True     138
NaN       90
Name: count, dtype: int64

 restecg
restecg
normal              551
lv hypertrophy      188
st-t abnormality    179
NaN                   2
Name: count, dtype: int64

 exang
exang
False    528
True     337
NaN       55
Name: count, dtype: int64

 slope
slope
flat           345
NaN            309
upsloping      203
downsloping     63
Name: count, dtype: int64

 thal
thal
NaN                  486
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64

In [8]:
print(df["num"].value_counts())

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [9]:
print(df.isnull().sum())

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [10]:
df[["ca","thal"]].head(20)

     ca               thal
0   0.0       fixed defect
1   3.0             normal
2   2.0  reversable defect
3   0.0             normal
4   0.0             normal
5   0.0             normal
6   2.0             normal
7   0.0             normal
8   1.0  reversable defect
9   0.0  reversable defect
10  0.0       fixed defect
11  0.0             normal
12  1.0       fixed defect
13  0.0  reversable defect
14  0.0  reversable defect
15  0.0             normal
16  0.0  reversable defect
17  0.0             normal
18  0.0             normal
19  0.0             normal

In [11]:
print(df["ca"].value_counts(dropna=False))
print("\n")
print(df["thal"].value_counts(dropna=False))

ca
NaN    611
0.0    181
1.0     67
2.0     41
3.0     20
Name: count, dtype: int64


thal
NaN                  486
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64

In [12]:
df["target"] = (df["num"] > 0).astype(int)

In [13]:
df["target"].value_counts()

target
1    509
0    411
Name: count, dtype: int64

In [14]:
df.drop("id", axis=1, inplace=True)

In [15]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num', 'target'],
      dtype='object')

In [16]:
df.drop("num", axis=1, inplace=True)

In [17]:
df.columns

Index(['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [18]:
df.drop("dataset", axis=1, inplace=True)

In [19]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [20]:
df.isnull().sum().sort_values(ascending=False)

ca          611
thal        486
slope       309
fbs          90
oldpeak      62
trestbps     59
thalch       55
exang        55
chol         30
restecg       2
age           0
sex           0
cp            0
target        0
dtype: int64

In [21]:
df.drop(["ca", "thal"], axis=1, inplace=True)

In [27]:
num_cols = ["oldpeak", "trestbps", "thalch", "chol"]
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [28]:
for col in ["fbs", "exang", "restecg", "slope"]:
    df[col] = df[col].fillna(df[col].mode()[0])

In [29]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

In [30]:
df.to_csv("clean_data.csv", index=False)
print("Saved successfully")

Saved successfully